#!/bin/bash
# Version 1.02
# By Paul Basehore


struptime=`/usr/sbin/asterisk -rx "core show uptime" | awk '{print $2,$3,$4,$5}'`
struptime1=${struptime%,}
strdayshours=${struptime1%%:*}' Hours, '
strminutes=${struptime1##*:}' Minutes'

echo "Asterisk Uptime -" $strdayshours$strminutes

exit 0
