#!/bin/bash
#
# chkconfig: - 90 12
# description: CAMBOX Start boot
#

# Source function library.
. /etc/init.d/functions

testVPN() 
{
	ping 169.254.0.1 -c 1 ;

	if [ $? -gt 0 ] ; 
	then 
		echo "VPN is not running!";
		exit 1;
	else
		ping 169.254.61.10 -c 1 ; 
		if [ $? -gt 0 ] ; 
		then 
			echo "VPN funcionando, todavia, rotas nao":
			echo "Refazendo roteamento";
			/sbin/ip route del 169.254.0.0/16 
			/sbin/ip route add 169.254.0.0/16 via 169.254.0.1
			netstat -anr
		else
			echo "VPN Funcionando e rotas tambem"; 
		fi;
	fi ;

}

stopme()
{
	echo "Script de STOP nao habilitado";
}

case "$1" in
start)
testVPN;
;;
stop)
stopme
;;
status)
status network
;;
restart|reload|condrestart)
stopme
startme
;;
*)
echo $"Usage: $0 {start|stop|restart|reload|status}"
exit 1
esac


