#!/bin/bash
#
# chkconfig: - 90 12
# description: CAMBOX Start boot
#

# Source function library.
. /etc/init.d/functions

startme() {
	echo "Habilitando comunicacao"
	/usr/sbin/kswitch-vlan eth0 vlan reset
	/usr/sbin/kswitch-vlan eth0 vlan set 10,0,U
	/usr/sbin/kswitch-vlan eth0 vlan set 30,1,U
	/usr/sbin/kswitch-vlan eth0 vlan set 20,3,U
	/usr/sbin/kswitch-vlan eth0 vlan set 20,2,U

	/etc/init.d/network restart

	/etc/init.d/dhcpd restart

}

stopme() {
	echo "Script de STOP nao habilitado"
}

case "$1" in
start)
	startme
	;;
stop)
	stopme
	;;
status)
	status network
	;;
restart | reload | condrestart)
	stopme
	startme
	;;
*)
	echo $"Usage: $0 {start|stop|restart|reload|status}"
	exit 1
	;;
esac
